name: timl-classification
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6  # earthengine doesn't play with python 3.7
  - dataclasses  # only introduced in python 3.7
  - black
  - pandas
  - matplotlib
  - pip
  - pytorch=1.6.0
  - tqdm
  - scikit-learn
  - platformdirs=2.3.0
  - pip:
      - learn2learn==0.1.3
      - dill
      - openpyxl
      - cropharvest==0.3.0
