name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: install mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: crop_classification/environment.yml
        environment-name: timl-classification
    - name: Run tests
      run: |
        cd crop_classification
        python -m black --check --diff ..
        cd ..
